import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:provider/provider.dart';

import 'core/routes.dart';
import 'core/theme.dart';
import 'providers/auth_provider.dart';
import 'providers/cart_provider.dart';
import 'providers/order_provider.dart';
import 'screens/splash_screen.dart';
import 'screens/onboarding_screen.dart';
import 'screens/auth/phone_login_screen.dart';
import 'screens/auth/otp_screen.dart';
import 'screens/home/home_screen.dart';
import 'screens/restaurant/restaurant_screen.dart';
import 'screens/cart/cart_screen.dart';
import 'screens/order_tracking/order_tracking_screen.dart';
import 'screens/profile/profile_screen.dart';

// Generated by Flutter's localization tool — run: flutter gen-l10n
// import 'package:flutter_gen/gen_l10n/app_localizations.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(const DalboApp());
}

class DalboApp extends StatelessWidget {
  const DalboApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(create: (_) => CartProvider()),
        ChangeNotifierProvider(create: (_) => OrderProvider()),
      ],
      child: MaterialApp(
        title: 'Dalbo',
        debugShowCheckedModeBanner: false,
        theme: appTheme(),

        // Localizations — English default, Somali ready
        localizationsDelegates: const [
          GlobalMaterialLocalizations.delegate,
          GlobalWidgetsLocalizations.delegate,
          GlobalCupertinoLocalizations.delegate,
          // AppLocalizations.delegate,   // uncomment after running flutter gen-l10n
        ],
        supportedLocales: const [
          Locale('en'),  // English
          Locale('so'),  // Somali
        ],

        // ── Named routes ───────────────────────────────────────────────
        initialRoute: AppRoutes.splash,
        routes: {
          AppRoutes.splash:        (_) => const SplashScreen(),
          AppRoutes.onboarding:    (_) => const OnboardingScreen(),
          AppRoutes.phoneLogin:    (_) => const PhoneLoginScreen(),
          AppRoutes.otpVerify:     (_) => const OtpScreen(),
          AppRoutes.home:          (_) => const HomeScreen(),
          AppRoutes.restaurant:    (_) => const RestaurantScreen(),
          AppRoutes.cart:          (_) => const CartScreen(),
          AppRoutes.orderTracking: (_) => const OrderTrackingScreen(),
          AppRoutes.profile:       (_) => const ProfileScreen(),
        },
      ),
    );
  }
}
