name: dalbo_app
description: Dalbo Food Delivery — Hargeisa, Somaliland
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # State management (simple and beginner-friendly)
  provider: ^6.1.2

  # HTTP calls to our backend
  http: ^1.2.1

  # Persist login token between app restarts
  shared_preferences: ^2.2.3

  # Load images from the internet with caching
  cached_network_image: ^3.3.1

  # Nice OTP input field (the boxes you type one digit each)
  pinput: ^4.0.0

  # Icons pack (optional, adds more icons)
  cupertino_icons: ^1.0.2

flutter:
  uses-material-design: true

  # Localization
  generate: true

  assets:
    - assets/images/
